### ISSUE TITLE
setDefaultPushCallback deprecated

### ISSUE THREAD

**Issue by f3lixz** [ParsePlatform/PushTutorial#13]
I would very much appreciate it if you could update the android tutorial to be up-to-date with the SDK.

Thanks in advance.

**Comment by skykelsey** [comment]
:+1:

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-8** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
