### ISSUE TITLE
crashes when wifi turn off

### ISSUE THREAD

**Issue by amcamc** [ParsePlatform/PushTutorial#14]
the application crash on background when no internet connection enabled

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by facebook-github-bot-8** [comment]
Thank you for your patience. After 30 days with no updates from the core team, we're closing out the issue. If you're still experiencing the problem described, please reopen the issue - thanks!
