### ISSUE TITLE
gradle setup please

### ISSUE THREAD

**Issue by jjhesk** [ParsePlatform/PushTutorial#15]
is that possible issue a gradle setup instruction for us? thx

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by a--hoang** [comment]
I have just submitted a pull request for the gradle setup. feel free to check out my fork.

**Comment by bnham** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
