### ISSUE TITLE
android/pushnotifications/Application.java

### ISSUE THREAD

**Issue by JoaquimLey** [ParsePlatform/PushTutorial#16]
Using deprecated method to setup.

Please update this project to match the Web tutorial.

**Comment by a--hoang** [comment]
I have just submitted a pull request to do so - feel free to check out my fork.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by bnham** [comment]
Thank you for your patience. We're going to close out this issue. If you're still experiencing the problem described, please reopen the issue - thanks!
