### ISSUE TITLE
PushNotifications - Unity

### ISSUE THREAD

**Issue by architrathi** [ParsePlatform/PushTutorial#24]
The sample project for Unity does not work. Please update!

**Comment by hallucinogen** [comment]
Sorry for very late reply, but this issue should be fixed today!

**Comment by architrathi** [comment]
Doesn't still work. Has this been corrected?

**Comment by hallucinogen** [comment]
Yes. What kind of Platform and what version of Unity are you using. This should work for Unity iOS and Unity Android, with Unity 4.6.x. You need to manually create the `Scene` on Unity 5.x.x, but it will work.

**Comment by architrathi** [comment]
Unity Android on 5.0.1f1. After manually creating the scene and creating an android build, it does not start on the phone. Shows an error message and closes on startup.

**Comment by hallucinogen** [comment]
Just tested it manually, and it works. Can you:
1. After it crashed, try open the app again.
2. Try make a Google Android Project build, and build it manually using Android Studio.
