### ISSUE TITLE
Why is the sample still 1.4.3?

### ISSUE THREAD

**Issue by JeffAtPropeller** [ParsePlatform/PushTutorial#27]
I tried to get 1.9.3 to work in my app. It worked fine on Android 5 but none of the earlier versions I tested. Thinking I got some config wrong I checked the tutorial code only to find out it's using 1.4.3. I swapped out the library with the one in this project and tweaked the code to register pushes the old way and now I get them on all my tested versions. 

Why is this so far behind? Especially when push can be rather difficult to configure...

**Comment by hallucinogen** [comment]
This is being addressed in #19
